name: Éditions Vodary, Paris
url: https://vodary.paris.fr
description: <strong>Éditions Vodary</strong> is an open-access pub­li­sher in Paris. It pub­li­shes li­te­ra­ry works in di­verse lan­guages and scripts, ran­ging from main­stream to exo­tic and even planned ones.

permalink: /book/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
include: ['_redirects']

collections:
  - forerunners   
